move $algo $algo_dest
move $angular $angular_dest
move $cloud $cloud_dest
move $cwm $cwm_dest
move $db $db_dest
move $dm $dm_dest
move $devops $devops_dest
move $excel $excel_dest
move $finance $finance_dest
move $git $git_dest
move $health $health_dest
move $infosec $infosec_dest
move $java $java_dest
move $js $js_dest
move $learning $learning_dest
move $linux $linux_dest
move $misc $misc_dest
move $mobile $mobile_dest
move $networking $networking_dest
move $next $next_dest
move $node $node_dest
move $photoshop $photoshop_dest
move $powerpoint $powerpoint_dest
move $python $python_dest
move $react $react_dest
move $seo $seo_dest
move $stacks $stacks_dest
move $ui $ui_dest
move $vue $vue_dest
move $web3 $web3_dest
move $win $win_dest
move $wp $wp_dest